#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'

  require 'ostruct'

  require_relative 'replan_lexer'

class ReplanParser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 90)
  attr_accessor :v_f, :v_f_time, :v_s, :v_ul, :v_uu, :v_o, :v_carry, :v_top,
    :v_time_block, :v_interval, :v_next_prefix, :v_next, :v_carry_parent

  def parse(input)
    scan_str(input)

    OpenStruct.new(
      fixed:       self.v_f,
      fixed_time:  self.v_f_time,
      skip:        self.v_s,
      update:      self.v_ul,
      update_full: self.v_uu,
      once:        self.v_o,
      carry:       self.v_carry,
      carry_parent: self.v_carry_parent,
      top:         self.v_top,
      time_block:  self.v_time_block,
      interval:    self.v_interval,
      next_prefix: self.v_next_prefix,
      next:        self.v_next,
    )
  end

  private

  # Assign to self.<var>, checking that it's not already assigned.
  #
  def checked_assign(var, value)
    self.send(var).nil? ?
      self.send("#{var}=", value) :
      raise("Option '#{var}' is already assigned: #{self.send(var)}")
  end

  def assign_time_block(value)
    self.v_time_block.nil? ?
      self.v_time_block = value :
      raise("A time-block flag is already assigned: #{self.v_time_block}")
  end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    12,    13,    14,    15,    19,     2,    20,    21,    22,    23,
    12,    13,    14,    15,    19,     3,    20,    21,    22,    23,
    12,    13,    14,    15,    19,     4,    20,    21,    22,    12,
    13,    14,    15,    19,    52,    20,    21,    22,    41,     5,
    53,    35,    43,    44,    24,    12,    13,    14,    15,    27,
    28,    29,    30,    31,    43,    44,    43,    44,    39,    45,
    46,    47,    48,    51 ]

racc_action_check = [
     4,     4,     4,     4,     4,     0,     4,     4,     4,     4,
    10,    10,    10,    10,    10,     1,    10,    10,    10,    10,
    17,    17,    17,    17,    17,     2,    17,    17,    17,    34,
    34,    34,    34,    34,    48,    34,    34,    34,    24,     3,
    48,    16,    24,    24,     7,     7,     7,     7,     7,     8,
     8,     8,     8,     8,    45,    45,    46,    46,    19,    27,
    28,    43,    44,    47 ]

racc_action_pointer = [
     3,    15,    22,    39,    -4,   nil,   nil,    41,    35,   nil,
     6,   nil,   nil,   nil,   nil,   nil,    38,    16,   nil,    49,
   nil,   nil,   nil,   nil,    23,   nil,   nil,    56,    57,   nil,
   nil,   nil,   nil,   nil,    25,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    58,    59,    35,    37,    49,    19,   nil,
   nil,   nil,   nil,   nil ]

racc_action_default = [
   -40,   -40,   -40,   -40,   -13,    54,    -1,   -40,   -40,    -4,
   -15,    -7,    -9,   -10,   -11,   -12,   -40,   -16,   -18,   -22,
   -24,   -25,   -26,   -27,   -40,    -6,    -3,   -28,   -30,   -32,
   -33,   -34,    -5,    -8,   -17,   -14,   -19,   -20,   -21,   -23,
    -2,   -35,   -36,   -40,   -40,   -40,   -40,   -40,   -40,   -29,
   -31,   -37,   -38,   -39 ]

racc_goto_table = [
    42,    37,     9,    11,    17,     1,    25,     6,    32,    33,
    34,     7,    40,     8,    26,    10,    16,   nil,    37,   nil,
   nil,    49,    50 ]

racc_goto_check = [
    14,    12,     7,     9,    11,     1,     9,     2,     7,     9,
    11,     3,     4,     5,     6,     8,    10,   nil,    12,   nil,
   nil,    14,    14 ]

racc_goto_pointer = [
   nil,     5,     3,     7,   -12,     9,     6,    -2,    11,    -1,
    12,     0,   -16,   nil,   -24 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    38,
   nil,   nil,    18,    36,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  3, 23, :_reduce_none,
  3, 24, :_reduce_none,
  2, 24, :_reduce_none,
  1, 25, :_reduce_none,
  2, 25, :_reduce_none,
  2, 25, :_reduce_none,
  1, 30, :_reduce_none,
  2, 30, :_reduce_none,
  1, 31, :_reduce_9,
  1, 31, :_reduce_10,
  1, 31, :_reduce_11,
  1, 31, :_reduce_12,
  0, 27, :_reduce_none,
  2, 27, :_reduce_none,
  1, 32, :_reduce_none,
  1, 32, :_reduce_none,
  2, 32, :_reduce_none,
  1, 33, :_reduce_none,
  2, 33, :_reduce_none,
  1, 35, :_reduce_none,
  1, 35, :_reduce_none,
  1, 34, :_reduce_22,
  2, 34, :_reduce_23,
  1, 34, :_reduce_24,
  1, 34, :_reduce_25,
  1, 34, :_reduce_26,
  1, 29, :_reduce_27,
  1, 28, :_reduce_28,
  3, 28, :_reduce_29,
  1, 28, :_reduce_30,
  3, 28, :_reduce_31,
  1, 28, :_reduce_32,
  1, 28, :_reduce_33,
  1, 28, :_reduce_34,
  1, 26, :_reduce_35,
  1, 26, :_reduce_none,
  3, 36, :_reduce_37,
  3, 36, :_reduce_38,
  3, 36, :_reduce_39 ]

racc_reduce_n = 40

racc_shift_n = 54

racc_token_table = {
  false => 0,
  :error => 1,
  :REPLAN => 2,
  :WHITESPACE => 3,
  :CARRY => 4,
  :CARRY_PARENT => 5,
  :TOP => 6,
  :TIME_BLOCK => 7,
  :F => 8,
  :TIME => 9,
  :S => 10,
  :U_LOW => 11,
  :U_UP => 12,
  :ONCE => 13,
  :INTERVAL => 14,
  :DAY => 15,
  :LAST_DAY => 16,
  :LAST_DAYNUM => 17,
  :FIRST_DAY => 18,
  :IN => 19,
  :ON => 20,
  :MONTH_DAY => 21 }

racc_nt_base = 22

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "REPLAN",
  "WHITESPACE",
  "CARRY",
  "CARRY_PARENT",
  "TOP",
  "TIME_BLOCK",
  "F",
  "TIME",
  "S",
  "U_LOW",
  "U_UP",
  "ONCE",
  "INTERVAL",
  "DAY",
  "LAST_DAY",
  "LAST_DAYNUM",
  "FIRST_DAY",
  "IN",
  "ON",
  "MONTH_DAY",
  "$start",
  "expression",
  "definition",
  "once_options",
  "once_next",
  "options_optional",
  "period_and_next",
  "option_once",
  "shared_options",
  "once_option",
  "options",
  "recurring_options",
  "recurring_option",
  "option",
  "next" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

module_eval(<<'.,.,', 'parser.y', 23)
  def _reduce_9(val, _values, result)
     checked_assign(:v_carry, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 24)
  def _reduce_10(val, _values, result)
     checked_assign(:v_carry_parent, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 25)
  def _reduce_11(val, _values, result)
     checked_assign(:v_top, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 26)
  def _reduce_12(val, _values, result)
     assign_time_block(val.fetch(0))
    result
  end
.,.,

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

module_eval(<<'.,.,', 'parser.y', 50)
  def _reduce_22(val, _values, result)
     checked_assign(:v_f, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 51)
  def _reduce_23(val, _values, result)
     checked_assign(:v_f, val.fetch(0)); checked_assign(:v_f_time, val.fetch(1))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 52)
  def _reduce_24(val, _values, result)
     checked_assign(:v_s, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 53)
  def _reduce_25(val, _values, result)
     checked_assign(:v_ul, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 54)
  def _reduce_26(val, _values, result)
     checked_assign(:v_uu, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 58)
  def _reduce_27(val, _values, result)
     checked_assign(:v_o, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 62)
  def _reduce_28(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 63)
  def _reduce_29(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 64)
  def _reduce_30(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 65)
  def _reduce_31(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 66)
  def _reduce_32(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 67)
  def _reduce_33(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 68)
  def _reduce_34(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 72)
  def _reduce_35(val, _values, result)
     self.v_next = val.fetch(0)
    result
  end
.,.,

# reduce 36 omitted

module_eval(<<'.,.,', 'parser.y', 77)
  def _reduce_37(val, _values, result)
     self.v_next_prefix = val.fetch(0); self.v_next = val.fetch(2)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 78)
  def _reduce_38(val, _values, result)
     self.v_next_prefix = val.fetch(0); self.v_next = val.fetch(2)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 79)
  def _reduce_39(val, _values, result)
     self.v_next_prefix = val.fetch(0); self.v_next = val.fetch(2)
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class ReplanParser
