#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.8.1
# from Racc grammar file "parser.y".
#

require 'racc/parser.rb'

  require 'ostruct'

  require_relative 'replan_lexer'

class ReplanParser < Racc::Parser

module_eval(<<'...end parser.y/module_eval...', 'parser.y', 70)
  attr_accessor :v_f, :v_f_time, :v_s, :v_ul, :v_uu, :v_o, :v_carry, :v_top,
    :v_time_block, :v_interval, :v_next_prefix, :v_next

  def parse(input)
    scan_str(input)

    OpenStruct.new(
      fixed:       self.v_f,
      fixed_time:  self.v_f_time,
      skip:        self.v_s,
      update:      self.v_ul,
      update_full: self.v_uu,
      once:        self.v_o,
      carry:       self.v_carry,
      top:         self.v_top,
      time_block:  self.v_time_block,
      interval:    self.v_interval,
      next_prefix: self.v_next_prefix,
      next:        self.v_next,
    )
  end

  private

  # Assign to self.<var>, checking that it's not already assigned.
  #
  def checked_assign(var, value)
    self.send(var).nil? ?
      self.send("#{var}=", value) :
      raise("Option '#{var}' is already assigned: #{self.send(var)}")
  end

  def assign_time_block(value)
    self.v_time_block.nil? ?
      self.v_time_block = value :
      raise("A time-block flag is already assigned: #{self.v_time_block}")
  end
...end parser.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    16,    17,    18,    12,     2,    13,    14,    15,    19,    31,
    16,    17,    18,    12,    36,    13,    14,    15,    35,    37,
    36,     3,    36,     4,    35,    37,    35,    37,    26,    27,
    28,    29,    30,    20,    22,    23,    24,     5,    33,    38,
    39,    40,    43 ]

racc_action_check = [
     4,     4,     4,     4,     0,     4,     4,     4,     4,    10,
    10,    10,    10,    10,    20,    10,    10,    10,    20,    20,
    38,     1,    39,     2,    38,    38,    39,    39,     8,     8,
     8,     8,     8,     7,     7,     7,     7,     3,    12,    26,
    27,    35,    40 ]

racc_action_pointer = [
     2,    21,    20,    37,    -4,   nil,   nil,    30,    15,   nil,
     6,   nil,    30,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     0,   nil,   nil,   nil,   nil,   nil,    36,    37,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    38,   nil,   nil,     6,     8,
    29,   nil,   nil,   nil ]

racc_action_default = [
   -32,   -32,   -32,   -32,    -9,    44,    -1,   -32,   -32,    -4,
   -32,   -12,   -13,   -15,   -16,   -17,   -18,   -19,   -20,   -21,
   -32,    -5,    -6,    -7,    -8,    -3,   -22,   -24,   -26,   -27,
   -28,   -10,   -11,   -14,    -2,   -32,   -30,   -31,   -32,   -32,
   -32,   -23,   -25,   -29 ]

racc_goto_table = [
    34,    11,     1,     6,     7,     8,    25,    32,     9,    21,
    10,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    41,    42 ]

racc_goto_check = [
     4,    10,     1,     2,     3,     5,     6,    10,     7,     8,
     9,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     4,     4 ]

racc_goto_pointer = [
   nil,     2,    -1,     0,   -20,     1,    -2,     4,     2,     6,
    -3 ]

racc_goto_default = [
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  3, 21, :_reduce_none,
  3, 22, :_reduce_none,
  2, 22, :_reduce_none,
  1, 23, :_reduce_none,
  2, 23, :_reduce_none,
  1, 28, :_reduce_6,
  1, 28, :_reduce_7,
  1, 28, :_reduce_8,
  0, 25, :_reduce_none,
  2, 25, :_reduce_none,
  2, 29, :_reduce_none,
  1, 29, :_reduce_none,
  1, 30, :_reduce_13,
  2, 30, :_reduce_14,
  1, 30, :_reduce_15,
  1, 30, :_reduce_16,
  1, 30, :_reduce_17,
  1, 30, :_reduce_18,
  1, 30, :_reduce_19,
  1, 30, :_reduce_20,
  1, 27, :_reduce_21,
  1, 26, :_reduce_22,
  3, 26, :_reduce_23,
  1, 26, :_reduce_24,
  3, 26, :_reduce_25,
  1, 26, :_reduce_26,
  1, 26, :_reduce_27,
  1, 26, :_reduce_28,
  3, 24, :_reduce_29,
  1, 24, :_reduce_30,
  1, 24, :_reduce_31 ]

racc_reduce_n = 32

racc_shift_n = 44

racc_token_table = {
  false => 0,
  :error => 1,
  :REPLAN => 2,
  :WHITESPACE => 3,
  :CARRY => 4,
  :TOP => 5,
  :TIME_BLOCK => 6,
  :F => 7,
  :TIME => 8,
  :S => 9,
  :U_LOW => 10,
  :U_UP => 11,
  :ONCE => 12,
  :INTERVAL => 13,
  :DAY => 14,
  :LAST_DAY => 15,
  :LAST_DAYNUM => 16,
  :FIRST_DAY => 17,
  :IN => 18,
  :MONTH_DAY => 19 }

racc_nt_base = 20

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]
Ractor.make_shareable(Racc_arg) if defined?(Ractor)

Racc_token_to_s_table = [
  "$end",
  "error",
  "REPLAN",
  "WHITESPACE",
  "CARRY",
  "TOP",
  "TIME_BLOCK",
  "F",
  "TIME",
  "S",
  "U_LOW",
  "U_UP",
  "ONCE",
  "INTERVAL",
  "DAY",
  "LAST_DAY",
  "LAST_DAYNUM",
  "FIRST_DAY",
  "IN",
  "MONTH_DAY",
  "$start",
  "expression",
  "definition",
  "once_options",
  "next",
  "options_optional",
  "period_and_next",
  "option_once",
  "once_option",
  "options",
  "option" ]
Ractor.make_shareable(Racc_token_to_s_table) if defined?(Ractor)

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

module_eval(<<'.,.,', 'parser.y', 17)
  def _reduce_6(val, _values, result)
     checked_assign(:v_carry, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 18)
  def _reduce_7(val, _values, result)
     checked_assign(:v_top, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 19)
  def _reduce_8(val, _values, result)
     assign_time_block(val.fetch(0))
    result
  end
.,.,

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

module_eval(<<'.,.,', 'parser.y', 32)
  def _reduce_13(val, _values, result)
     checked_assign(:v_f, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 33)
  def _reduce_14(val, _values, result)
     checked_assign(:v_f, val.fetch(0)); checked_assign(:v_f_time, val.fetch(1))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 34)
  def _reduce_15(val, _values, result)
     checked_assign(:v_s, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 35)
  def _reduce_16(val, _values, result)
     checked_assign(:v_ul, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 36)
  def _reduce_17(val, _values, result)
     checked_assign(:v_uu, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 37)
  def _reduce_18(val, _values, result)
     checked_assign(:v_carry, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 38)
  def _reduce_19(val, _values, result)
     checked_assign(:v_top, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 39)
  def _reduce_20(val, _values, result)
     assign_time_block(val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 43)
  def _reduce_21(val, _values, result)
     checked_assign(:v_o, val.fetch(0))
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 47)
  def _reduce_22(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 48)
  def _reduce_23(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 49)
  def _reduce_24(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 50)
  def _reduce_25(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 51)
  def _reduce_26(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 52)
  def _reduce_27(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 53)
  def _reduce_28(val, _values, result)
     self.v_interval = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 57)
  def _reduce_29(val, _values, result)
     self.v_next_prefix = val.fetch(0); self.v_next = val.fetch(2)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 58)
  def _reduce_30(val, _values, result)
     self.v_next = val.fetch(0)
    result
  end
.,.,

module_eval(<<'.,.,', 'parser.y', 59)
  def _reduce_31(val, _values, result)
     self.v_next = val.fetch(0)
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class ReplanParser
